# -*- coding: utf-8 -*-
"""Example (PEFT and Instruction Following).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cLzt0y6FTyDnZcRLyckAdZflhtemhsGp
"""

!pip install -q sympy torch transformers peft accelerate datasets evaluate

import torch
import transformers
import evaluate

print("torch:", torch.__version__)
print("transformers:", transformers.__version__)
print("cuda:", torch.cuda.is_available())
print("has _utils:", hasattr(torch, "_utils"))
print(evaluate.__version__)

from datasets import load_dataset
from transformers import AutoTokenizer, AutoModelForSequenceClassification

ds = load_dataset("cornell-movie-review-data/rotten_tomatoes")
checkpoint = "bert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)
model = AutoModelForSequenceClassification.from_pretrained(checkpoint, num_labels=2)

from transformers import TrainingArguments, Trainer
from peft import LoraConfig, TaskType, get_peft_model
import numpy as np
import evaluate

metric = evaluate.load("accuracy")

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=-1)
    return metric.compute(predictions=preds, references=labels)

def tokenize_function(examples):
    return tokenizer(examples["text"], truncation=True)

tokenized_ds = ds.map(tokenize_function, batched=True)

sample = tokenized_ds["train"][0]

print("input_ids:")
print(torch.tensor(sample["input_ids"]))

print("\nattention_mask:")
print(torch.tensor(sample["attention_mask"]))

print("\ntoken_type_ids:")
print(torch.tensor(sample["token_type_ids"]))

print("\nlabel:")
print(torch.tensor(sample["label"]))

# === LoRA ===
peft_config = LoraConfig(
    task_type=TaskType.SEQ_CLS,
    r=8,
    lora_alpha=16,
    lora_dropout=0.1,
    target_modules=["query", "value"],
    modules_to_save=["classifier"],
)

model = get_peft_model(model, peft_config)
model.print_trainable_parameters()

training_args = TrainingArguments(
    output_dir="./results",
    eval_strategy="epoch",
    save_strategy="no",
    num_train_epochs=5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    report_to="none"
)

print("learning_rate:", training_args.learning_rate)
print("weight_decay:", training_args.weight_decay)
print("warmup_steps:", training_args.warmup_steps)
print("max_grad_norm:", training_args.max_grad_norm)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_ds["train"],
    eval_dataset=tokenized_ds["validation"],
    processing_class=tokenizer,
    compute_metrics=compute_metrics,
)

trainer.train()
trainer.evaluate()

!pip -q install sentencepiece

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

model_name = "google/flan-t5-small"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

instruction = """
Summarize the following review in one sentence:
The movie was visually stunning, with breathtaking cinematography and carefully crafted scenes that made every frame look like a piece of art.
The acting was also excellent, with the lead performers delivering emotional and convincing performances that kept the audience engaged throughout most of the film.
However, despite its strong visual and acting elements, the story felt too predictable.
Many plot twists could be easily anticipated, and the narrative followed a familiar formula without offering much originality.
"""

inputs = tokenizer(instruction, return_tensors="pt")
outputs = model.generate(**inputs, max_new_tokens=50)

result = tokenizer.decode(outputs[0], skip_special_tokens=True)
print(result)

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

model_name = "google/flan-t5-base"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

instruction = """
Summarize the following review in one sentence:
The movie was visually stunning, with breathtaking cinematography and carefully crafted scenes that made every frame look like a piece of art.
The acting was also excellent, with the lead performers delivering emotional and convincing performances that kept the audience engaged throughout most of the film.
However, despite its strong visual and acting elements, the story felt too predictable.
Many plot twists could be easily anticipated, and the narrative followed a familiar formula without offering much originality.
"""

inputs = tokenizer(instruction, return_tensors="pt")
outputs = model.generate(**inputs, max_new_tokens=50)

result = tokenizer.decode(outputs[0], skip_special_tokens=True)
print(result)

from transformers import AutoTokenizer, AutoModelForCausalLM
import torch

model_name = "Qwen/Qwen2.5-0.5B-Instruct"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    torch_dtype="auto",
    device_map="auto"
)

instruction = """
Summarize the following review in one sentence:
The movie was visually stunning, with breathtaking cinematography and carefully crafted scenes that made every frame look like a piece of art.
The acting was also excellent, with the lead performers delivering emotional and convincing performances that kept the audience engaged throughout most of the film.
However, despite its strong visual and acting elements, the story felt too predictable.
Many plot twists could be easily anticipated, and the narrative followed a familiar formula without offering much originality.
"""

messages = [
    {"role": "system", "content": "You are a helpful assistant."},
    {"role": "user", "content": instruction}
]

text = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
inputs = tokenizer(text, return_tensors="pt").to(model.device)
outputs = model.generate(**inputs,max_new_tokens=60)

result = tokenizer.decode(
    outputs[0][inputs.input_ids.shape[1]:],
    skip_special_tokens=True
)

print(result)

