# -*- coding: utf-8 -*-
"""Example (PEFT and Instruction Following).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cLzt0y6FTyDnZcRLyckAdZflhtemhsGp
"""

!pip install -q sympy torch transformers peft accelerate datasets evaluate

import torch
import transformers
import evaluate

print("torch:", torch.__version__)
print("transformers:", transformers.__version__)
print("cuda:", torch.cuda.is_available())
print("has _utils:", hasattr(torch, "_utils"))
print(evaluate.__version__)

from datasets import load_dataset
from transformers import AutoTokenizer, AutoModelForSequenceClassification

ds = load_dataset("cornell-movie-review-data/rotten_tomatoes")
checkpoint = "bert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)
model = AutoModelForSequenceClassification.from_pretrained(checkpoint, num_labels=2)

from transformers import TrainingArguments, Trainer
from peft import LoraConfig, TaskType, get_peft_model
import numpy as np
import evaluate

metric = evaluate.load("accuracy")

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=-1)
    return metric.compute(predictions=preds, references=labels)

def tokenize_function(examples):
    return tokenizer(examples["text"], truncation=True)

tokenized_ds = ds.map(tokenize_function, batched=True)

sample = tokenized_ds["train"][0]

print("input_ids:")
print(torch.tensor(sample["input_ids"]))

print("\nattention_mask:")
print(torch.tensor(sample["attention_mask"]))

print("\ntoken_type_ids:")
print(torch.tensor(sample["token_type_ids"]))

print("\nlabel:")
print(torch.tensor(sample["label"]))

# === LoRA ===
peft_config = LoraConfig(
    task_type=TaskType.SEQ_CLS,
    r=8,
    lora_alpha=16,
    lora_dropout=0.1,
    target_modules=["query", "value"],
    modules_to_save=["classifier"],
)

model = get_peft_model(model, peft_config)
model.print_trainable_parameters()

training_args = TrainingArguments(
    output_dir="./results",
    eval_strategy="epoch",
    save_strategy="no",
    num_train_epochs=5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    report_to="none"
)

print("learning_rate:", training_args.learning_rate)
print("weight_decay:", training_args.weight_decay)
print("warmup_steps:", training_args.warmup_steps)
print("max_grad_norm:", training_args.max_grad_norm)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_ds["train"],
    eval_dataset=tokenized_ds["validation"],
    processing_class=tokenizer,
    compute_metrics=compute_metrics,
)

trainer.train()
trainer.evaluate()





